# Generated by Django 5.0 on 2024-09-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
