# Generated by Django 5.0 on 2024-09-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_alter_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hide_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='hide_likes',
            field=models.BooleanField(default=False),
        ),
    ]
