# Generated by Django 5.0 on 2024-10-16 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0008_like_enabled_like_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_reply', to='Profiles.comment'),
        ),
    ]
