# Generated by Django 5.0 on 2024-10-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0010_post_ai_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ai_check',
            new_name='ai_reported',
        ),
        migrations.AddField(
            model_name='comment',
            name='ai_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_reported',
            field=models.BooleanField(default=False),
        ),
    ]
