# Generated by Django 5.0 on 2024-10-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0013_posts_count_latest_recommendation_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts_count_latest',
        ),
    ]
