# Generated by Django 5.0 on 2024-10-30 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0014_delete_posts_count_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation_posts',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_posts', to='Profiles.profile'),
        ),
    ]
