# Generated by Django 5.0 on 2024-10-31 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0015_recommendation_posts_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation_Reels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.JSONField()),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_reels', to='Profiles.profile')),
            ],
        ),
    ]
