# Generated by Django 5.0 on 2024-11-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0016_recommendation_reels'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='user/reels/thumbnails/'),
        ),
    ]
