# Generated by Django 5.0 on 2024-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportpost',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
