# Generated by Django 5.0 on 2024-10-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0002_alter_reportpost_unique_together_reportpost_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
