# Generated by Django 5.0 on 2024-11-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0004_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
