# Generated by Django 5.0 on 2024-10-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_message_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
    ]
