# Generated by Django 5.0 on 2024-10-24 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_chatroomdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomdeleted',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Chat.chatroom'),
        ),
    ]
