# Generated by Django 5.0 on 2024-10-24 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0011_alter_chatroomdeleted_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroomdeleted',
            old_name='message',
            new_name='chatroom',
        ),
    ]
