# Generated by Django 5.0 on 2024-10-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0012_rename_message_chatroomdeleted_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomuser',
            name='in_chat',
            field=models.BooleanField(default=False),
        ),
    ]
