# Generated by Django 5.0 on 2024-11-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
