# Generated by Django 5.0 on 2024-11-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0015_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
