# Generated by Django 5.0 on 2024-11-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0017_chatroomdeleted_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomdeleted',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
    ]
