# Generated by Django 5.0 on 2024-11-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0018_alter_chatroomdeleted_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomdeleted',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
